In [1]:
import numpy as np

In [3]:
np.random.choice(['tom','dick','harry'], (3,3))

array([['harry', 'tom', 'dick'],
       ['harry', 'tom', 'tom'],
       ['harry', 'dick', 'tom']], dtype='<U5')

In [4]:
ntrials = 10000
n_dice = 3

In [7]:
x = np.random.choice([1,2,3,4,5,6], ntrials*n_dice)

In [12]:
x = x.reshape(ntrials,n_dice)

In [20]:
x[0]

array([1, 1, 3])

In [25]:
(x.sum(axis=1) > 12).astype(int).mean()


0.2539

In [26]:
%matplotlib notebook

In [28]:
chance = (x.sum(axis=1) > 12).mean()

In [29]:
p_nap = .3

In [30]:
naps = np.random.random((10,2)) <= p_nap

In [31]:
naps

array([[False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True,  True],
       [False,  True],
       [ True, False],
       [False, False],
       [False, False],
       [False, False]])

In [32]:
naps.sum(axis=1)

array([0, 0, 1, 1, 2, 1, 1, 0, 0, 0])

In [33]:
naps.sum(axis=1) >= 1

array([False, False,  True,  True,  True,  True,  True, False, False,
       False])

In [34]:
(naps.sum(axis=1) >= 1).mean()

0.5

In [58]:
import pandas as pd

In [67]:
ntrials = 30000
n_dice = 3
rolls = np.random.choice([1,2,3,4,5,6], ntrials*n_dice).reshape((ntrials, n_dice))

In [68]:
df = pd.DataFrame(rolls)

In [69]:
df.dtypes

0    int64
1    int64
2    int64
dtype: object

In [70]:
df.apply(lambda row: 3 in row.values, axis=1).mean()

0.4177666666666667

In [71]:
np.random.seed(123)

In [72]:
np.random.choice(['a','b','c'], 3)

array(['c', 'b', 'c'], dtype='<U1')